### ISSUE TITLE
Services: Add common exception handlers

### ISSUE THREAD

**Issue by tmrietz** [taylor-jones/employee-recognition-portal#12]
Services should probably all be in a try/catch pattern, which means there's potential to have really repetitive code at least in the catch blocks. May want to have some common exception handlers.

**Comment by taylor-jones** [comment]
@tmrietz You've since taken care of this one, yeah?

**Comment by tmrietz** [comment]
Not really, actually ☹️. We might be able to put this in a common package if we really want to or find the time? IMO most of the service layer for db persisted objects (eg: not signatures) should return an Optional. That pattern's flexible at the service layer and seems like an ok design that avoids just throwing exceptions all over the place.

The controllers sit closest to the network layer, so having a common handler at that layer that returns ResponseEntity objects would be nice too. Ultimately comes down to need and available time though.

**Comment by tmrietz** [comment]
Closing this. Perhaps one day.
