### ISSUE TITLE
Rearrange Client File Structure

### ISSUE THREAD

**Issue by TuckerL-OSU** [taylor-jones/employee-recognition-portal#22]
Need to partially redo some file structure, because the nav bar SHOULD NOT be in the app.component.

**Comment by taylor-jones** [comment]
I'm thinking at this point we aren't really interested in doing this anymore. Seems we're too close to being done to worry about this, given that all the functionality is there. What do you guys think @TuckerL-OSU @tmrietz?

**Comment by TuckerL-OSU** [comment]
We got it close enough with the user account context related nav bars
