### ISSUE TITLE
Add Admin-Guard

### ISSUE THREAD

**Issue by TuckerL-OSU** [taylor-jones/employee-recognition-portal#23]
Similar to Auth-Guard, but is used to check if they Authenticated user is an admin.

**Comment by taylor-jones** [comment]
@TuckerL-OSU If I recall, you took care of this one already, right? Or else we decided to go a different direction? Do we think this issue still needs attention?

**Comment by TuckerL-OSU** [comment]
We went a different direction with this. It can be closed
