### ISSUE TITLE
Conditionally show nav links based on authentication.

### ISSUE THREAD

**Issue by taylor-jones** [taylor-jones/employee-recognition-portal#28]
I think it would be nice if we were able to conditionally show/hide certain nav links based on whether or not the user was logged in and/or what type of user was logged in. I think it would make the user experience seem a lot more dynamic.

**Comment by TuckerL-OSU** [comment]
This is related to the restructuring of the client so that it's not using the app.component stuff.

**Comment by taylor-jones** [comment]
Oh, right on. Feel free to close this issue if we already have another one that addresses this.

**Comment by taylor-jones** [comment]
This was resolved in #42.
