### ISSUE TITLE
Logout makes 4 requests

### ISSUE THREAD

**Issue by taylor-jones** [taylor-jones/employee-recognition-portal#32]
I noticed that logging out triggers four POST requests to /api/logout. Probably not a critical fix, but maybe worth looking into.

**Comment by tmrietz** [comment]
I think I saw in the call to /api/logout there’s a statement that’s something like: retry(3)

I’d bet that’s where this is happening

**Comment by taylor-jones** [comment]
Yeah, @tmrietz you were right. I've updated it to only call once in #53 .
