### ISSUE TITLE
Frontend email validation

### ISSUE THREAD

**Issue by TuckerL-OSU** [taylor-jones/employee-recognition-portal#62]
Need to add form validation for email on the front end.

**Comment by TuckerL-OSU** [comment]
Currently malformed email causes user to still be inserted into db, but recovery questions are not.

**Comment by taylor-jones** [comment]
I'm not sure I understand the issue. Where on the frontend? During user registration?

**Comment by TuckerL-OSU** [comment]
O this was in the create an account that I made that breaks with a malformed email

**Comment by taylor-jones** [comment]
This is handled in #68. It doesn't provide the same level of thorough validation for each of the 3 user creation form steps, but it does provide the thorough validation for the 1st form (the one w/ the username, passwords, and email). It should be good to go, now.
